"""只依赖 bmo_check_core 的诊断入口；不读取 static/dynamic 内部状态。"""

from bmo_check_core.diagnostics import (
    DynamicDiagnosticSnapshot,
    EvidenceSnapshot,
    SnapshotError,
    StaticDiagnosticSnapshot,
)
from .correlation import (
    CorrelationError,
    CorrelationKey,
    CorrelationRecord,
    CorrelationStatus,
    DiagnosticCorrelationReport,
    correlate_unknowns,
)
from .classification import (
    ClassificationError,
    ClassificationResult,
    DiagnosticRootCause,
    ROOT_CAUSE_REGISTRY,
    RootCauseDescriptor,
    classify_unknown,
    classify_unknowns,
    validate_root_cause_registry,
)
from .report import (
    CertificateIdentity,
    DiagnosticCoverage,
    DiagnosticReport,
    DiagnosticReportError,
    build_diagnostic_report,
    diagnose,
)
from .affine import (
    AffineObservationError,
    AffineValidationReport,
    ObservedAffinePattern,
    ObservedAffineStatus,
    ObservedAffineThread,
    ObservedOverlap,
    affine_pattern_to_dict,
    affine_report_to_dict,
    affine_report_to_json,
    build_affine_validation_report,
    save_affine_report,
    site_filter_for_affine_unknowns,
    summarize_observed_affine_patterns,
)

__all__ = [
    "DynamicDiagnosticSnapshot",
    "EvidenceSnapshot",
    "SnapshotError",
    "StaticDiagnosticSnapshot",
    "CorrelationError",
    "CorrelationKey",
    "CorrelationRecord",
    "CorrelationStatus",
    "DiagnosticCorrelationReport",
    "correlate_unknowns",
    "ClassificationError",
    "ClassificationResult",
    "DiagnosticRootCause",
    "ROOT_CAUSE_REGISTRY",
    "RootCauseDescriptor",
    "classify_unknown",
    "classify_unknowns",
    "validate_root_cause_registry",
    "CertificateIdentity",
    "DiagnosticCoverage",
    "DiagnosticReport",
    "DiagnosticReportError",
    "build_diagnostic_report",
    "diagnose",
    "AffineObservationError",
    "AffineValidationReport",
    "ObservedAffinePattern",
    "ObservedAffineStatus",
    "ObservedAffineThread",
    "ObservedOverlap",
    "affine_pattern_to_dict",
    "affine_report_to_dict",
    "affine_report_to_json",
    "build_affine_validation_report",
    "save_affine_report",
    "site_filter_for_affine_unknowns",
    "summarize_observed_affine_patterns",
]
